# # Feature Selection
# FEATS = [
#     #'userID', # 추가 시 valid 증가, public 감소. 과적합 의심
#     "KnowledgeTag",
#     'solve_count_per_test', 'number_of_users_per_test', 
#     #'not_solving_count_per_test', 'problem_solving_rate_per_test', # 시험지 별 안 푼 문제 개수, 문제를 푼 비율 추가 시 -> valid score감소, public score 감소
#     "answerRate_per_tag", "answerCount_per_tag", "answerVar_per_tag", "answerStd_per_tag",
#     "tag_count",
#     "mean_elp_tag_all_mean", 
#     #"mean_elp_tag_all_sum", "mean_elp_tag_all_var", "mean_elp_tag_all_std",
#     "mean_elp_tag_o_mean", 
#     #"mean_elp_tag_o_sum", "mean_elp_tag_o_var", "mean_elp_tag_o_std",
#     "mean_elp_tag_x_mean", 
#     #"mean_elp_tag_x_sum", "mean_elp_tag_x_var", "mean_elp_tag_x_std",
#     "answerRate_per_test", "answerCount_per_test", "answerVar_per_test", "answerStd_per_test",
#     "cum_answerRate_per_user",
#     "problem_correct_per_user",
#     "problem_solved_per_user",
#     "mean_elp_ass_all_mean", 
#     #"mean_elp_ass_all_sum", "mean_elp_ass_all_var", "mean_elp_ass_all_std",
#     "mean_elp_ass_o_mean", 
#     #"mean_elp_ass_o_sum", "mean_elp_ass_o_var", "mean_elp_ass_o_std",
#     "mean_elp_ass_x_mean", 
#     #"mean_elp_ass_x_sum", "mean_elp_ass_x_var", "mean_elp_ass_x_std",
#     "answerRate_per_ass", "answerCount_per_ass", "answerVar_per_ass", "answerStd_per_ass",
#     "elapsed",
#     'elapsed_shift',
#     "category",
#     "acc_answerRate_per_cat",
#     "acc_count_per_cat",
#     "acc_elapsed_per_cat",
#     "correct_answer_per_cat",
#     "test_number",
#     "mean_elp_pnum_all_mean", 
#     #"mean_elp_pnum_all_sum", "mean_elp_pnum_all_var", "mean_elp_pnum_all_std",
#     "mean_elp_pnum_o_mean", 
#     #"mean_elp_pnum_o_sum", "mean_elp_pnum_o_var", "mean_elp_pnum_o_std",
#     "mean_elp_pnum_x_mean", 
#     #"mean_elp_pnum_x_sum", "mean_elp_pnum_x_var", "mean_elp_pnum_x_std",
#     "acc_tag_count_per_user",
#     "problem_count",
#     "problem_number",
#     "answerRate_per_pnum", "answerCount_per_pnum", "answerVar_per_pnum", "answerStd_per_pnum",
#     "problem_position",
#     'timeDelta_userAverage',
#     'timestep_1', 'timestep_2', 'timestep_3', 'timestep_4', 'timestep_5', #제거 시 valid, public score 모두 감소
#     "median_elapsed_wrong_users", "median_elapsed_correct_users"
# ]

# Feature Selection
FEATS = [
    #'userID', # 추가 시 valid 증가, public 감소. 과적합 의심
    "KnowledgeTag",
    'solve_count_per_test', 'number_of_users_per_test', 
    #'not_solving_count_per_test', 'problem_solving_rate_per_test', # 시험지 별 안 푼 문제 개수, 문제를 푼 비율 추가 시 -> valid score감소, public score 감소
    "answerRate_per_tag", "answerCount_per_tag", "answerVar_per_tag", "answerStd_per_tag",
    "tag_count",
    "mean_elp_tag_all_mean", 
    #"mean_elp_tag_all_sum", "mean_elp_tag_all_var", "mean_elp_tag_all_std",
    "mean_elp_tag_o_mean", 
    #"mean_elp_tag_o_sum", "mean_elp_tag_o_var", "mean_elp_tag_o_std",
    "mean_elp_tag_x_mean", 
    #"mean_elp_tag_x_sum", "mean_elp_tag_x_var", "mean_elp_tag_x_std",
    "answerRate_per_test", "answerCount_per_test", "answerVar_per_test", "answerStd_per_test",
    "mean_elp_ass_all_mean", 
    #"mean_elp_ass_all_sum", "mean_elp_ass_all_var", "mean_elp_ass_all_std",
    "mean_elp_ass_o_mean", 
    #"mean_elp_ass_o_sum", "mean_elp_ass_o_var", "mean_elp_ass_o_std",
    "mean_elp_ass_x_mean", 
    #"mean_elp_ass_x_sum", "mean_elp_ass_x_var", "mean_elp_ass_x_std",
    "answerRate_per_ass", "answerCount_per_ass", "answerVar_per_ass", "answerStd_per_ass",
    "elapsed",
    'elapsed_shift',
    "category",
    "acc_answerRate_per_cat",
    "acc_count_per_cat",
    "acc_elapsed_per_cat",
    "correct_answer_per_cat",
    "test_number",
    "mean_elp_pnum_all_mean", 
    #"mean_elp_pnum_all_sum", "mean_elp_pnum_all_var", "mean_elp_pnum_all_std",
    "mean_elp_pnum_o_mean", 
    #"mean_elp_pnum_o_sum", "mean_elp_pnum_o_var", "mean_elp_pnum_o_std",
    "mean_elp_pnum_x_mean", 
    #"mean_elp_pnum_x_sum", "mean_elp_pnum_x_var", "mean_elp_pnum_x_std",
    "acc_tag_count_per_user",
    "problem_count",
    "problem_number",
    "answerRate_per_pnum", "answerCount_per_pnum", "answerVar_per_pnum", "answerStd_per_pnum",
    "problem_position",
    'timeDelta_userAverage',
    'timestep_1', 'timestep_2', 'timestep_3', 'timestep_4', 'timestep_5', #제거 시 valid, public score 모두 감소
    "median_elapsed_wrong_users", "median_elapsed_correct_users",
    #"mean_elapsed_wrong_users", "mean_elapsed_correct_users",
    "cum_answerRate_per_user", "problem_correct_per_user", "problem_solved_per_user",
    #'correct_mean_per_user', 'correct_var_per_user', 'correct_std_per_user',
    #'number_of_sloved_per_tag', 'correct_mean_per_tag', 'correct_var_per_tag', 'correct_std_per_tag',
]

print(len(FEATS))